---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dongggg
  labels:
    app: dongggg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dongggg
  template:
    metadata:
      labels:
        app: dongggg
    spec:
      containers:
        - name: dongggg
          image: docker.io/phengbunath/dongggg:2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080